// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seqcnvnloqhszkxbgwri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcWNudm5sb3Foc3preGJnd3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjc5ODMsImV4cCI6MjA4ODYwMzk4M30.ZrAxggnEvUzn8u_laCJ7bHTPLhW8zN3yeqXq7nIhDUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});